spring:

      redis:
        host: v4bug.com
        password: teampass
hello:
      myname: bwy


file:
  image-path: c:/temp/image
  max-file-size: 5242880 #5MB
  server-port: 6435
  server-host: localhost

project:
  controller:
    allowed:
      origins: http://car.v4bug.com
      methods: GET, POST, PUT, DELETE, OPTIONS
    domain: http://car.v4bug.com #后端域名
    verify:
      interval: 1000
      width: 100
      height: 30
      number: 4

emailServer:
    serverhost: smtp.wmgblog.shop
    user: hanshuocar@wmgblog.shop
    password: hs12345678+

