spring:
      datasource:
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url:   jdbc:mysql://123.207.172.223:3306/car?useUnicode=true&characterEncoding=utf8
        username:  team
        password:  teampass
        type: org.apache.commons.dbcp2.BasicDataSource
        dbcp2:
          max-wait-millis:  5000
          min-idle:  5
          initial-size: 5
          connection-properties: characterEncoding=utf8
          max-total:  10
      mvc:
        view:
          suffix: .jsp
          prefix: /
hello:
      myname: bwy
mybatis:
        type-aliases-package: cn.saytime.bean

file:
  image-path: c:/temp/image
  max-file-size: 5242880 #5MB

project:
  controller:
    allowed:
      origins: a.com, b.com, c.com
      methods: GET, POST, PUT, DELETE, OPTIONS
    domain: http://localhost:8008 #后端域名
    domain-front: http://localhost:8080 #前端域名
    verify:
      interval: 1000
