spring:
       datasource:
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url:   jdbc:mysql://123.207.172.223:3306/car?useUnicode=true&characterEncoding=utf8
        username:  team
        password:  teampass
        type: org.apache.commons.dbcp2.BasicDataSource
        dbcp2:
          max-wait-millis:  5000
          min-idle:  5
          initial-size: 5
          connection-properties: characterEncoding=utf8
          max-total:  10
hello:
      myname: bwy
mybatis:
        type-aliases-package: cn.saytime.bean

